FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PEPTIDE_HOST=0.0.0.0
ENV PEPTIDE_PORT=8080
ENV PEPTIDE_DB=/data/app.db
ENV PEPTIDE_TIMEZONE=America/Los_Angeles

WORKDIR /app
COPY app ./app
COPY static ./static

EXPOSE 8080
VOLUME ["/data"]

CMD ["python", "-m", "app.server"]
